appId: org.cru.godtools.beta
name: TRACT - Teach Me to Share (traintool)
tags:
  - generated
  - tract
  - tool-traintool
---
- launchApp:
    stopApp: true
- runFlow: ../../../helpers/dismiss_onboarding.yaml
- openLink: "godtools://org.cru.godtools/tool/tract/traintool/en"
- runFlow: ../../../helpers/dismiss_open_app_prompt.yaml
- assertVisible:
    id: "Tract"
- assertVisible: "Teach Me to Share"
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/00-0-introscreen-xml"
- swipe:
    start: 90%, 50%
    end: 10%, 50%
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/01-01-howtoshare-xml"
- swipe:
    start: 90%, 50%
    end: 10%, 50%
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/02-02-begin-xml"
- swipe:
    start: 90%, 50%
    end: 10%, 50%
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/03-05-keepinmind-xml"
- swipe:
    start: 90%, 50%
    end: 10%, 50%
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/04-03-transition-xml"
- swipe:
    start: 90%, 50%
    end: 10%, 50%
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/05-04-picktool-xml"
- swipe:
    start: 90%, 50%
    end: 10%, 50%
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/06-06-anythingelse-xml"
- swipe:
    start: 90%, 50%
    end: 10%, 50%
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/07-08-moretotry-xml"
- swipe:
    start: 90%, 50%
    end: 10%, 50%
- takeScreenshot: "${SNAPSHOT_DIR}/traintool/08-07-ready-xml"
