appId: org.cru.godtools.beta
name: Launch to language settings
---
- launchApp:
    stopApp: true
- runFlow: dismiss_onboarding.yaml
- openLink: "godtools://org.cru.godtools/ui_tests/settings/language"
- runFlow: dismiss_open_app_prompt.yaml
- assertVisible:
    id: "Language Settings"
